import Bg from "../../../assets/bg.png";
import Zebet from "../../../assets/zebet.png";
import ZebetSlide from "../../../assets/zebetslide.png";
import OneEx from "../../../assets/1xbet.png";
import OneExSlide from "../../../assets/1xbetslide.png";
import kma from "../../../assets/kma.png";
import kmaSlide from "../../../assets/bfSlide.png";
import home from "../../../assets/landing.jpg";
import socials from "../../../assets/socials.jpg";
import background2 from "../../../assets/back2.png";
import login from "../../../assets/logins.png";
import KMA_LOGO_WHITE from "../../../assets/KMA_WHITE.png";
import ads_one from "../../../assets/ads1.png";
import ads_two from "../../../assets/ads2.png";
import adscoke from "../../../assets/adscoke.png";
import adscasiona from "../../../assets/adscasiona.png";
import ads_three from "../../../assets/ads3.png";

export const bg = Bg;
export const OneExbet = OneEx;
export const OneExbetSlide = OneExSlide;
export const ZEBET = Zebet;
export const ZEBETSlide = ZebetSlide;
export const KMASlide = kmaSlide;
export const KMA = kma;
export const HOME = home;
export const SOCIALS = socials; 
export const BACKGROUND = background2; 
export const LOGIN = login; 
export const KMA_LOGO_WH = KMA_LOGO_WHITE; 
export const ADS_ONE = ads_one; 
export const ADS_TWO  = ads_two; 
export const ADS_THREE = ads_three; 
export const ADS_FOUR = adscoke; 
export const ADS_FIVE  = adscasiona; 
